### ISSUE TITLE
Cirque trackpad question

### ISSUE THREAD

**Issue by MinHyeong-Lee** [chrishoage/spleeb#3]
Thanks to your help, switch works well, and the OLED works well! :)
The last step is the cirque trackpad.

If I use chrishoage keymap, do I just touch it to use the cirque trackpad?
I removed the R1 resistor for I2C operation.

**mcuconf.h**
```C
#pragma once

#include_next <mcuconf.h>

#undef RP_I2C_USE_I2C1
#define RP_I2C_USE_I2C1 TRUE
```

**halconf.h**
```C
#pragma once

#define HAL_USE_I2C TRUE

#include_next <halconf.h>
```

I checked datasheet for kb2040 that SDA and SCL are GP2, GP3 and I2C1
I don't think I did anything wrong in particular. Can you give me some advice to refer to for the cirque trackpad?

I really appreciate your help in resolving the problem.😁

**Comment by chrishoage** [comment]
> I checked datasheet for kb2040 that SDA and SCL are GP2, GP3 and I2C1

Since the oled is working for you I don't think you have any issue with configuration. 

>  I don't think I did anything wrong in particular. Can you give me some advice to refer to for the cirque trackpad?

It's difficult to say with out being able to debug myself, however you can compile the firmware in debug mode - you should see logs if it detects the touchpad over i2c. 

I would double check the wiring to ensure all the wires are going to the right spots on the PCB and the touchpad. 

Beyond that it's difficult to say what may be the issue. 

If you have further questions while trying to debug this please reach out!

**Comment by MinHyeong-Lee** [comment]
> 

There is a possibility that the cirque trackpad I purchased is defective, so I will buy more spare parts and test it. Thank you!

**Comment by chrishoage** [comment]
Some more ideas if you struggle with this 

1. I bought one of these while doing the firmware https://www.aliexpress.us/item/2255800970134605.html along with a 12 pin cable to match so I could test the touchpad with out soldering wires to the touchpad directly
2. If you have a spare kb2040 and a breadboard you can try making a simple qmk firmware that tries to get the touchpad to work
3. compile and load the i2c scanner and see if it can find both the oled and the touchpad https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey/keymaps/i2c_scanner
4. If you do buy an extra touchpad try getting it working with the breakout board i linked over SPI, a breadboard and a spare kb2040. Once you know it's working you can take off the resistor, rewire for i2c and again reconfigure and test 

Again since the OLED is functioning for you it's unlikely to be a configuration issue (assuming the touchpad is on the right half - since my firmware uses the right half as the master)

**Comment by MinHyeong-Lee** [comment]
Thank you! When the new touchpad arrives, I will test it with the method you told me

Anyway, can I ask about spleeb firmware?
Inspired by your firmware, I applied an independent encoder layer to other keyboard.

I have an RGB indicator on my keyboard, so I want to express colors according to the current encoder layer.

But I don't know how to use `spleeb_get_encoder_mode()` in keymap.c because I'm not good at C language. 

For example, in my keymap.c
```C
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
   switch (keycode) {
      case ENC_STR:
            if(spleeb_get_encoder_mode() === 0) rgblight_sethsv_at(HSV_RED, 2); // led 2
             blah blah // I want to get encoder layer at here and set rgb light
   }
}
```

When I use spleeb_get_encoder_mode() function at mykeyboard.c 
RGB Indicator not works (The light comes on and goes out right out)
```C
bool process_record_kb(uint16_t keycode, keyrecord_t* record) {
#ifdef SPLEEB_ENCODER_MODE_MAP_ENABLE
    switch (keycode) {
        case ENC_MODE_STEP_RIGHT:
            if (record->event.pressed) {
                spleeb_step_encoder_mode(&g_spleeb_config, 1);
                switch (spleeb_get_encoder_mode(&g_spleeb_config, 1)) {
                    case 0:
                        rgblight_sethsv_at(HSV_RED, 2); // led 2
                        break;
                    case 1:
                        rgblight_sethsv_at(HSV_GREEN, 2); // led 2
                        break;
                    case 2:
                        rgblight_sethsv_at(HSV_WHITE, 2); // led 2
                        break;
                    case 3:
                        rgblight_sethsv_at(HSV_YELLOW, 2); // led 2
                        break;
                }
            }
            break;
    }
#endif // SPLEEB_ENCODER_MODE_MAP_ENABLE

    return true;
}
```
Thank you always from the bottom of my heart.😊

**Comment by chrishoage** [comment]
> The light comes on and goes out right out

I unfortunately I have not worked with QMK and leds so I won't be super helpful here. 

Since the light is turning on it seems like you're on the right track.   Maybe something is turning off the LED somewhere? 

I will note that you can probably use the userland `process_record_user` for this in your keymap with out overriding any of the `process_record_kb` code. 

You can check if the keycode is `ENC_MODE_STEP_RIGHT` and change your lights there. You should be able to get the current encoder mode using the functions defined in spleeb.c from there

**Comment by MinHyeong-Lee** [comment]
> 

I used `qmk console` command for debugging.
Changes occur in the terminal for all keys except trackpad.

What's interesting is that if I touch the trackpad while plug in/out usb to spleeb, sometimes it automatically moves to layer3, which is the mouse layer. It makes me think trackpad is connected well??... Hmm.. 😓
But once layer move to layer 3, it doesn't come back to layer 1.

So I have to plug in/out usb for reboot my keyboard again.

I haven't tried a lot of debugging yet. I haven't checked how to use functions like dprintf() in the "spleeb.c", "keymap.c" file yet.

Thank you

**Comment by chrishoage** [comment]
Are you certain the trackpad is wired to the pcb correctly? The wiring will be mirrored. 

If the oled and the trackpad have the same wire order on both halves of the pcb that would be the issue - they should be mirrored

**Comment by MinHyeong-Lee** [comment]
> Are you certain the trackpad is wired to the pcb correctly? The wiring will be mirrored.
> 
> If the oled and the trackpad have the same wire order on both halves of the pcb that would be the issue - they should be mirrored

![CleanShot 2023-06-12 at 09 27 13@2x](https://github.com/chrishoage/spleeb/assets/48749902/96865b64-6d4f-46b2-8436-ce7ba55cde3d)

<img width="598" alt="image" src="https://github.com/chrishoage/spleeb/assets/48749902/e0bcea7a-4eb4-44e4-a6d4-0b0bb7bff2dd">

Is this right??

This is my right side of spleeb

**Comment by chrishoage** [comment]
The colors threw me off for a sec but yes that does appear to be correct 

I notice that you have quite long exposed wires connected to the pads. How are you testing the touchpad? Is it in the chassis? 

In any case it would be a good idea to make sure you don't have any shorts on those wires when using them. 

They look like they have enough bare wire exposed that they could very easily touch.

**Comment by MinHyeong-Lee** [comment]
> The colors threw me off for a sec but yes that does appear to be correct
> 
> I notice that you have quite long exposed wires connected to the pads. How are you testing the touchpad? Is it in the chassis?
> 
> In any case it would be a good idea to make sure you don't have any shorts on those wires when using them.
> 
> They look like they have enough bare wire exposed that they could very easily touch.

Cirque trackpad is being tested without a case.
Just test the trackpad like in the picture.

If the solder direction is not a problem, I should check the wires and other problems again.

Thanks..

**Comment by chrishoage** [comment]
Unless you have been ridiculously careful when testing I fear you may have shorted the trackpad 

In the  future when soldering the pads do not leave so much bare wire that the wire can touch when moved around. 

Seeing your picture my gut feeling is you may have shorted and killed the touchpad (maybe, it's difficult to say)

**Comment by MinHyeong-Lee** [comment]
<img width="307" alt="image" src="https://github.com/chrishoage/spleeb/assets/48749902/0ab5ec43-70ff-4f23-ba5d-6bffeb12e672">

II bought a new trackpad and this time I cut the wire short..

As soon as I connect to the keyboard, the mouse moves for a few seconds and the trackpad doesn't work again
😂 My KB2040 is offer 3.3V and I think I'm having issues elsewhere.
I don't think there's any more hope. I already bought 4 trackpads.

**Comment by chrishoage** [comment]
These wires look much better! 

> As soon as I connect to the keyboard, the mouse moves for a few seconds and the trackpad doesn't work again

Does this happen every time you power the keyboard? Is this movent repeatable? 

>  I don't think there's any more hope. I already bought 4 trackpads.

I think there is certainly still hope! It is just difficult for me to offer advice when I can't try things myself. You will need to spend time debugging what the problem is. 

As I mentioned previously my suggestion before you modified the new trackpad was to try to get it working with that breakout board and a flat flexible cable (both of these can be bought very cheaply on aliexpress)  

Trying my steps will help narrow down the issue. 

If you can get it working with a spare KB2040 and the breakout board connected to a trackpad then you can use what you learned to figure out what may be the issue with it connected to the keyboard 

If you decide to try to debug this further and you have questions please feel free to reach out, I will be happy to answer anything I can. 

Ultimately you are the one in front of the hardware, so you are the best equipped to try to debug what may be the issue here.

**Comment by MinHyeong-Lee** [comment]
Thank you Chris Hoage :)
I just tested with another KB2040.
Cirque trackpad on my friend's spleeb works well.
But after I unplug JST cable and plug in again, it didn't work again.
I think the cirque trackpad is normal. Wire seems to be the problem. Sometimes it works, sometimes it doesn't.

![CleanShot 2023-06-23 at 08 33 08@2x](https://github.com/chrishoage/spleeb/assets/48749902/0f5fbd42-cd41-423f-9eea-adcb37b9a414)

I want to show you my left side of spleeb haha
I'll show you my right side after solving problem..

Thanks again.
Have a nice day!

**Comment by chrishoage** [comment]
The left side looks great!!

>  I just tested with another KB2040.
> Cirque trackpad on my friend's spleeb works well.
> But after I unplug JST cable and plug in again, it didn't work again.

Something I didn't think to ask before, but your comment here made me curious. 

Have you tested continuity of the JST-PH connection with a multi-meter? 

I'm wondering if there is a crimp that isn't making good connection with the wire? 

Testing the crimp to the spot on the trackpad will ensure you are getting continuity between the trackpad and the PCB. 

The fact that your friends keyboard trackpad is working is a really good sign, and shows that it's the KB2040 can totally run this. 

Maybe it was a wiring issue after all (I just didn't think to suggest testing the crimps)

**Comment by MinHyeong-Lee** [comment]
I tested JST-PH connection with a multi-meter.
Voltage was 3.28V.
And I add a i2c scanning code in firmware from this repo https://github.com/qmk/qmk_firmware/blob/master/keyboards/handwired/onekey/keymaps/i2c_scanner/keymap.c

![image](https://github.com/chrishoage/spleeb/assets/48749902/25261c4f-0ec2-4c12-ad76-8a30a0e048a5)

On right side I2C device found at address 0x2A <- I think this means solder joints and wires are right...

Everything seems normal, it's hard to find the cause. haha

**Comment by chrishoage** [comment]
oh? This is very good news. This is one of the troubleshooting steps I recommended originally.  

If it can find the device then there may be a configuration issue somewhere. 

I still think it would be a good idea to try a different KB2040 and set it up to get the touchpad working. 

Unfortunately it's still very difficult to debug this remotely, however the fact that the i2c scanner can find the device means that the device is likely working properly

**Comment by MinHyeong-Lee** [comment]
> oh? This is very good news. This is one of the troubleshooting steps I recommended originally.
> 
> If it can find the device then there may be a configuration issue somewhere.
> 
> I still think it would be a good idea to try a different KB2040 and set it up to get the touchpad working.
> 
> Unfortunately it's still very difficult to debug this remotely, however the fact that the i2c scanner can find the device means that the device is likely working properly

Chris!! Finally It works.

I don't know why my keyboard's trackpad didn't work.
I still don't know the exact reason.
However, it does not work immediately after copying the uf2 file for firmware change.

If I change the firmware and repeatedly unplug and plug in the usb, and then also unplug and plug the trrs cable, at some point the trackpad becomes stable. It keeps working well after that.

I got scared of changing firmware but now it works fine. I will use it well without changing the firmware..

![image](https://github.com/chrishoage/spleeb/assets/48749902/6b72f241-3c10-45af-b148-a9c44686f48c)

This is my keyboard.

Thank you Chris :)

**Comment by chrishoage** [comment]
Wonderful! Glad it's working. I don't know what the issue was either, but perhaps there was a corrupted firmware, or an old firmware with incorrect configuration. 

The keyboard looks great - enjoy! Let me know if I can be of any further assistance!
